#######################################################
# 
# AlexNet.py
# Python implementation of the Class AlexNet
# Generated by Enterprise Architect
# Created on:      05-5月-2017 16:52:57
# Original author: 圆润的馒头君
# 
#######################################################


class AlexNet:
    """此系统选用的是AlexNet结构
    """
    def __init__():
        # 当前运行模式=运行模式
        # 网络参数初始化


        pass

    def conv2d():
        # 卷积操作
        # return 图片编号+输出的图片格式


        pass

    def max_pool():
        # 池化操作
        # return 图片编号+输出的图片格式


        pass

    def norm():
        # 归一化操作
        # return 图片编号+输出的图片格式


        pass

    def Relu():
        # 全连接
        # return 图片编号+输出的图片格式


        pass

    def AlexNetTraining():
        #        for 符合格式的图片 in 图片路径
        #            卷积
        #            池化
        #            归一化
        #            ……
        #            全连接
        #            处理结果
        #            计算训练精度
        #        if 当前运行模式=训练
        #            return 训练精度
        #        else
        #            return 识别结果


        pass