#######################################################
# 
# OperationInterface.py
# Python implementation of the Class OperationInterface
# Generated by Enterprise Architect
# Created on:      05-5月-2017 17:02:24
# Original author: 圆润的馒头君
# 
#######################################################


class OperationInterface:
    """交通标示识别系统的GUI操作界面，有选择训练图片集路径、开始训练、选择识别图片路径、开始识别四个按钮
    """
    def CheckImageFormat(func):
        # def wrapper():
        #            图片路径=func()
        #            for 图片 in 图片路径
        #                if 图片格式符合要求
        #                    统计图片数量
        #                else
        #                    剔除不符合格式的图片
        #                    统计图片数量
        #            print 总图片数，不符合格式的图片数


        pass
	@CheckImageFormat
    def Load_Training_images(self):
        # 选择图片集或图片路径
        # return 图片集或图片路径


        pass

    def Start_recognize():
        # 图片路径 = Load_Training_images()
        # 运行模式=识别
        # Training_Model.Training(图片路径)
        # print 识别结束
        # print 识别结果


        pass

    def Start_Training():
        # 图片路径=Load_Training_images()
        # 运行模式=训练
        # Training_Model.Training(图片路径)
        # print 训练结束
        # print 训练精度


        pass